import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { RecaptchaProvider } from "@/providers/recaptcha-provider";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bloom Happy Day ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RecaptchaProvider>
      <html lang="en">
        <body className={`${poppins.className} antialiased`}>
          {children}
          <Toaster position="top-center" richColors />
        </body>
      </html>
    </RecaptchaProvider>
  );
}
